### ISSUE TITLE
Panic on initialize

### ISSUE THREAD

**Issue by chiefnoah** [embassy-rs/cyw43#1]
Looks like I'm seeing a hardfault/panic when initializing with `clm`:
```
panicked at 'range end index 5397528 out of range for slice of length 136', library/core/src/slice/index.rs:73:5
```

Full stacktrace:
```
0.002340 INFO  Hello World!
└─ cyw43_example_rpi_pico_w::____embassy_main_task::{async_fn#0} @ src/main.rs:44
0.272981 INFO  waiting for ping...
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
0.273472 INFO  ping ok
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
0.274477 INFO  waiting for clock...
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
0.274705 INFO  clock ok
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
0.275381 INFO  chip ID: 43439
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
0.279832 INFO  loading fw
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
3.706844 INFO  loading nvram
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
3.718915 INFO  starting up core...
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
3.741766 INFO  waiting for wifi init...
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
3.825687 INFO  init done 
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
3.825918 INFO  Downloading CLM...
└─ cyw43::{impl#2}::init::{async_fn#0} @ /home/noah/repos/cyw43/src/fmt.rs:138
3.846078 ERROR panicked at 'range end index 5397528 out of range for slice of length 136', library/core/src/slice/index.rs:73:5
└─ panic_probe::print_defmt::print @ /home/noah/.cargo/registry/src/github.com-1ecc6299db9ec823/panic-probe-0.3.0/src/lib.rs:91
────────────────────────────────────────────────────────────────────────────────
stack backtrace:
   0: HardFaultTrampoline
      <exception entry>
   1: lib::inline::__udf
        at ./asm/inline.rs:181:5
   2: __udf
        at ./asm/lib.rs:51:17
   3: cortex_m::asm::udf
        at /home/noah/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.5/src/asm.rs:43:5
   4: rust_begin_unwind
        at /home/noah/.cargo/registry/src/github.com-1ecc6299db9ec823/panic-probe-0.3.0/src/lib.rs:72:9
   5: core::panicking::panic_fmt
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/panicking.rs:142:14
   6: core::slice::index::slice_end_index_len_fail_rt
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/slice/index.rs:73:5
   7: core::ops::function::FnOnce::call_once
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/ops/function.rs:248:5
   8: core::intrinsics::const_eval_select
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/slice/index.rs:67:9
   9: core::slice::index::slice_end_index_len_fail
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/slice/index.rs:67:9
  10: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/slice/index.rs:304:13
  11: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/slice/index.rs:351:9
  12: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/slice/index.rs:18:9
  13: cyw43::Runner<PWR,SPI>::rx
        at /home/noah/repos/cyw43/src/lib.rs:830:33
  14: cyw43::Runner<PWR,SPI>::run::{{closure}}
        at /home/noah/repos/cyw43/src/lib.rs:709:21
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/future/mod.rs:91:19
  16: cyw43_example_rpi_pico_w::__wifi_task_task::{{closure}}
        at src/main.rs:34:17
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/future/mod.rs:91:19
  18: embassy::executor::raw::TaskStorage<F>::poll
  19: core::cell::Cell<T>::get
        at /rustc/1c7b36d4db582cb47513a6c7176baaec1c3346ab/library/core/src/cell.rs:451:18
  20: embassy::executor::raw::timer_queue::TimerQueue::update
        at /home/noah/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5f43c1d/embassy/src/executor/raw/timer_queue.rs:36:12
  21: embassy::executor::raw::Executor::poll::{{closure}}
        at /home/noah/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5f43c1d/embassy/src/executor/raw/mod.rs:423:13
  22: embassy::executor::raw::run_queue::RunQueue::dequeue_all
        at /home/noah/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5f43c1d/embassy/src/executor/raw/run_queue.rs:69:13
  23: embassy::executor::raw::Executor::poll
        at /home/noah/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5f43c1d/embassy/src/executor/raw/mod.rs:402:9
  24: cortex_m::asm::wfe
        at /home/noah/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.5/src/asm.rs:49:5
  25: embassy::executor::arch::Executor::run
        at /home/noah/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5f43c1d/embassy/src/executor/arch/cortex_m.rs:53:13
  26: cyw43_example_rpi_pico_w::__cortex_m_rt_main
        at src/main.rs:42:1
  27: main
        at src/main.rs:42:1
  28: Reset
  (HOST) ERROR the program panicked
```

This seems like a size mismatch, but there's also the possibility I broke my Pi W while soldering the headers :slightly_smiling_face:

**Comment by chiefnoah** [comment]
The issue appears to be related to `EventHeader` deserializing improperly such that `evt_data.datalen` is far larger than the real data buffer. I've not identified what the proper offset is for this header. Documentation on what `BcdHeader` can contain and where `EventHeader`'s format is defined would be appreciated.

**Comment by chiefnoah** [comment]
Some addition trace logging:
```
0.645521 TRACE tx SdpcmHeader { len: 1072, len_inv: 64463, sequence: 0, channel_and_flags: 0, next_length: 0, header_length: 12, wireless_flow_control: 0, bus_d
ata_credit: 0, reserved: [0, 0] }
0.645598 TRACE     CdcHeader { cmd: 263, len: 1044, flags: 2, id: 1, status: 0 }
0.645733 TRACE     [30, 04, cf, fb, 00, 00, 00, 0c, 00, 00, 00, 00, 07, 01, 00, 00, 14, 04, 00, 00, 02, 00, 01, 00, 00, 00, 00, 00, 63, 6c, 6d, 6c, 6f, 61, 64,
00, 02, 10, 02, 00, 00, 04, 00, 00, 00, 00, 00, 00]
0.647205 TRACE rx [00, 01, ff, fe, 00, 01, 00, 0c, 00, 00, 00, 00, 5c, 14, 04, 1a, 0c, 42, 88, 1d, 04, 4e, 1a, 01, 4c, 50, 02, a5, 2e, 59, 68, c2, 6c, 83, 23, 1
8, 2b, 48, d2, 20, 13, 58, c6, 24, f0, 55, 46, 14]
0.647370 TRACE rx SdpcmHeader { len: 256, len_inv: 65279, sequence: 0, channel_and_flags: 1, next_length: 0, header_length: 12, wireless_flow_control: 0, bus_da
ta_credit: 0, reserved: [0, 0] }
0.647448 TRACE     BcdHeader { flags: 92, priority: 20, flags2: 4, data_offset: 26 }
0.647500 TRACE     [c1, 54, 30, dc, 41, 00, 40, 00, 04, 10, 02, b0, 00, 21, 50, 10, 14, c0, 88, c7, ee, 90, 70, 08, 7f, 10, 02, a0, 0a, 04, a1, 54, 00, 22, 84,
91]
0.647686 TRACE rx    EventHeader { version: 32528, flags: 672, event_type: 168075604, status: 2262161, reason: 1045727236, auth_type: 138448032, datalen: 347347
8656, addr: [65, 145, 17, 225, 51, 5], ifname: [0, 139, 32, 1, 8, 0, 64, 68, 114, 53, 2, 132, 136, 5, 113, 76], ifidx: 32, bsscfgidx: 1 }
0.647905 ERROR panicked at 'range end index 3473478656 out of range for slice of length 64', library/core/src/slice/index.rs:73:5
```
Something is up with the deserialization of the `EventHeader`, none of these values look correct. Note, this `trace!` was added after `evt.byteswap()`, but putting it before yields similar, definitely wrong, results.

**Comment by mattiasgronlund** [comment]
The problem is that the given package is not even a WHD event.
So trying to read the EventHeader fails...

Seems like WHD events in reality are Broadcom brcmf events.

#3 should fix this issue.

**Comment by chiefnoah** [comment]
It makes it further from your fork, but I still get some sort of failure (though it's cryptic and possibly related to my probe)

**Comment by mattiasgronlund** [comment]
@chiefnoah, is it still panicing in the event handling?

If you provide the output I can try to understand what the problem is.

**Comment by chiefnoah** [comment]
No,  it gets further. There's a bunch of IOCTL Response messages, but it ultimately fails with some sort of probe error that I've never seen before:

```
0.891802 INFO  get clmload_status
0.892006 TRACE tx SdpcmHeader { len: 43, len_inv: 65492, sequence: 5, channel_and_flags: 0, next_length: 0, header_length: 12, wireless_flow_control: 0, bus_data_credit: 0, reserved: [0, 0] }
0.892048 TRACE     CdcHeader { cmd: 262, len: 15, flags: 0, id: 6, status: 0 }
0.892097 TRACE     [2b, 00, d4, ff, 05, 00, 00, 0c, 00, 00, 00, 00, 06, 01, 00, 00, 0f, 00, 00, 00, 00, 00, 06, 00, 00, 00, 00, 00, 63, 6c, 6d, 6c, 6f, 61, 64, 5f, 73, 74, 61, 74, 75, 73, 00, 00]
0.892967 TRACE rx [03, 01, fc, fe, 07, 00, 00, e4, 00, 16, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
0.893054 TRACE rx SdpcmHeader { len: 259, len_inv: 65276, sequence: 7, channel_and_flags: 0, next_length: 0, header_length: 228, wireless_flow_control: 0, bus_data_credit: 22, reserved: [0, 0] }
0.893104 TRACE     CdcHeader { cmd: 262, len: 15, flags: 0, id: 6, status: 0 }
0.893145 INFO  IOCTL Response: [00, 00, 00, 00, 6f, 61, 64, 5f, 73, 74, 61, 74, 75, 73, 00]
0.893261 INFO  Configuring misc stuff...
0.897747 INFO  set bus:txglom = [00, 00, 00, 00]
0.897916 TRACE tx SdpcmHeader { len: 92, len_inv: 65443, sequence: 6, channel_and_flags: 0, next_length: 0, header_length: 12, wireless_flow_control: 0, bus_data_credit: 0, reserved: [0, 0] }
0.897959 TRACE     CdcHeader { cmd: 263, len: 64, flags: 2, id: 7, status: 0 }
0.898023 TRACE     [5c, 00, a3, ff, 06, 00, 00, 0c, 00, 00, 00, 00, 07, 01, 00, 00, 40, 00, 00, 00, 02, 00, 07, 00, 00, 00, 00, 00, 62, 75, 73, 3a, 74, 78, 67, 6c, 6f, 6d, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
0.898621 TRACE rx [00, 01, ff, fe, 08, 00, 00, b0, 00, 17, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
0.898706 TRACE rx SdpcmHeader { len: 256, len_inv: 65279, sequence: 8, channel_and_flags: 0, next_length: 0, header_length: 176, wireless_flow_control: 0, bus_data_credit: 23, reserved: [0, 0] }
RTT error: Error communicating with probe: A core architecture specific error occured
────────────────────────────────────────────────────────────────────────────────
Error: A core architecture specific error occured

Caused by:
    0: Failed to read register DRW at address 0x0000000c
    1: An error specific to the selected architecture occured
    2: Target device did not respond to request
    ```

**Comment by Dirbaio** [comment]
"Error communicating with probe" is an error from probe-rs , not a panic from the firmware. I'm going to close this (also due to inactivity). If you see a panic please feel free to open a new issue with the stack trace.
